# config/requirements_config.yaml

employee_requirements: |
  We are seeking to contact individuals within companies who have a high likelihood of needing translation services. The ideal candidates will have the following characteristics:

  1. **Position**:
      - Titles such as Localization Manager, Global Marketing Manager, International Sales Manager, Content Manager, or any position related to international operations, marketing, sales, or content creation.
      - Roles that involve overseeing or managing content, communications, or marketing efforts that span multiple languages or regions.

  2. **Industry**:
      - Companies within industries that typically require translation services, such as legal, medical, technical, software, marketing, publishing, education, tourism, and hospitality.
      - Firms engaged in global commerce, international partnerships, or have a significant presence in non-native language markets.

  3. **Company Size and Reach**:
      - Companies of all sizes, but with a preference for those with an international footprint or aspirations.
      - Businesses involved in exporting goods or services, multinational corporations, or startups expanding into new regions.

  4. **Educational Background**:
      - Individuals with degrees or certifications in fields such as international business, marketing, communications, languages, or any area related to cross-cultural or global operations.
      - Relevant education that indicates an understanding of or experience with multilingual content or international market dynamics.

  5. **Skills and Experience**:
      - Proven experience in managing multilingual projects, international marketing campaigns, or localization efforts.
      - Familiarity with translation and localization tools, and processes.
      - Experience in coordinating with international teams or managing content that requires translation.

  6. **Company Attributes**:
      - Companies that demonstrate a need for multilingual communication, such as those with websites, marketing materials, software, or documentation available in multiple languages.
      - Firms that are actively expanding into new linguistic markets or regions, evidenced by recent news, job postings, or strategic initiatives.

  By identifying individuals who meet these criteria, we can more effectively offer our translation services to those who are most likely to benefit from them.